### ISSUE TITLE
Hey, wonder if you're interested in `Stream` API

### ISSUE THREAD

**Issue by ogios** [JakeStanger/system-tray#16]
Really enjoy `system-tray`, big thanks to you.

Recently i've been working on a `Stream` API which is able to run this without tokio.
it performs like this:
```rust 
    let client = Client::new().await.unwrap();
    let mut stream = client.create_stream().await.unwrap();

    while let Some(event) = stream.next().await {
        println!("{event:?}");
    }
```

and we can do this for zbus:
```toml
# Cargo.toml

[features]
default = ["tokio"]
unstable_stream = ["zbus/async-io", "dep:futures"]
tokio = ["zbus/tokio", "dep:tokio"]

[dependencies]
zbus = { version = "5.3", default-features = false, optional = true }
tokio = { version = "1", features = ["rt", "sync", "macros", "time"], optional = true }
futures = { version = "0.3.31", optional = true }
tracing = "0.1.41"
serde = { version = "1", features = ["derive"] }
thiserror = "2.0.11"
```

it is almost done https://github.com/ogios/system-tray-zbus5/pull/10, but of course it is the first time i write async rust code like this, so it's tagged `unstable`.

i can port it here if you are interested.
